### ISSUE TITLE
We find a bug when mysql table name have "_" 

### ISSUE THREAD

**Issue by uranusmars** [facebook/presto#3763]
The problem is when mysql have "_" in the table name the  "escapeNamePattern" function change the name.
So the sql can`t run on mysql.
In the file  presto-mysql/src/main/java/com/facebook/presto/plugin/mysql/MySqlClient.java    line 93  to line 97.
For example:  table "aaa_bbb" change to "aaa\\_bbb" .  
The bug find above release 0.119.

**Comment by sunli1223** [comment]
yes, the 0.123 version still have this problem .

**Comment by kokosing** [comment]
I can take care of this bug.

**Comment by kokosing** [comment]
This is the same as #3677

**Comment by kokosing** [comment]
@uranusmars `_` have to be escaped as it a wildcard which `represents any single character`, see: http://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#getSearchStringEscape()

I tried to reproduce it but with no success, everything seem to be working as expected. Here is my test which was expected to reproduce the issue, but it is passing: https://github.com/Teradata/presto/commit/185b2b762f4d28c49fdb8097a89da2eac2cbd090

com.facebook.presto.plugin.mysql.TestMySqlDistributedQueries#testDropTable should also fail because of described issue but it is passing.

Presto testing infrastructure is using mysql at 5.5.9 version.

I need more detailed information about how to reproduce it, or this issue is eligible to be closed as not being able to be reproduced.

**Comment by sunli1223** [comment]
@kokosing  the escape sql will like 'select * from test\_tables;', but this sql can not be execute，this problem  is same as postgresql.
I change code like  below worked fine.
```Java
 @Override
    protected ResultSet getTables(Connection connection, String schemaName, String tableName)
            throws SQLException
    {
        // MySQL maps their "database" to SQL catalogs and does not have schemas
        DatabaseMetaData metadata = connection.getMetaData();
       // String escape = metadata.getSearchStringEscape();
        return metadata.getTables(
                schemaName,
                null,
                tableName,
                new String[] {"TABLE"});
    }

```

**Comment by kokosing** [comment]
@sunli1223 I updated the test so it runs SELECT now, see https://github.com/Teradata/presto/commit/e9b91f7523945274fed30903162d1c7489739272.
It is still passing. I suspect it may have something related to your mysql server or jdbc configuration. Can you tell me what `metadata.getSearchStringEscape();` returns for you?

**Comment by sunli1223** [comment]
@kokosing  I used mysql-connector-java-5.1.35,metadata.getSearchStringEscape() will call 
```Java
com.mysql.jdbc.DatabaseMetaData.getSearchStringEscape(){
   return "\\";
}
```
so,return "\" from me. And the the same as postresql.

Jdbc document say"
```Text
This is the string that can be used to escape '_' or '' in the string pattern style catalog search parameters.

The '_' character represents any single character.

The '' character represents any sequence of zero or more characters.
```
I guess the Escape String is  used for some sql like "where field Like ' %a\%% ' ",but not for table name。

**Comment by kokosing** [comment]
@sunli1223 From jdbc documentation for ``DatabaseMetaData#getTables``
```
...
     * @param tableNamePattern a table name pattern; must match the
     *        table name as it is stored in the database
...
     * @see #getSearchStringEscape
```
and for ``DatabaseMetaData#getSearchStrnigEscape()``
```
     * Retrieves the string that can be used to escape wildcard characters.
     * This is the string that can be used to escape '_' or '%' in
     * the catalog search parameters that are a pattern (and therefore use one
     * of the wildcard characters).
```

As you can see escape string is used in pattern in catalog searches, and getTable is using it. IMO everything is ok in the code. I will try to repeat the tests with JDBC at version you specified to reproduce the problem.

**Comment by uranusmars** [comment]
@kokosing this is our mysql version

Server version: 5.6.25-73.1-log Percona Server (GPL), Release 73.1, Revision 07b797f

You can try to reproduce the problem.

**Comment by sunli1223** [comment]
@kokosing  The jdbc version is Included in presto. I test mysql versio with "5.5.31-MariaDB-log", "5.5.32-log" and "5.6.24-72.2-log" .I download the latest version presto-server-0.126 just now,then test.
```text
mysql> show tables from test_test;
+---------------------+
| Tables_in_test_test |
+---------------------+
| test                |
| test_abc            |
+---------------------+
2 rows in set

presto:default> show tables from mysql.test_test;
 Table 
-------
(0 rows)

Query 20151120_094143_00006_w8rni, FINISHED, 1 node
Splits: 2 total, 2 done (100.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

```
at the same time ,I run tcpdump to see the sql send to mysqlserver.below is the output
```text
sudo tcpdump -i lo -s 0 -l -w - dst port 3306|strings
tcpdump: listening on lo, link-type EN10MB (Ethernet), capture size 65535 bytes
root
mysql_native_password
['	J
[+	J
[0	J
/* mysql-connector-java-5.1.35 ( Revision: 5fb9c5849535c13917c2cf9baaece6ef9693ef27 ) */SHOW VARIABLES WHERE Variable_name ='language' OR Variable_name = 'net_write_timeout' OR Variable_name = 'interactive_timeout' OR Variable_name = 'wait_timeout' OR Variable_name = 'character_set_client' OR Variable_name = 'character_set_connection' OR Variable_name = 'character_set' OR Variable_name = 'character_set_server' OR Variable_name = 'tx_isolation' OR Variable_name = 'transaction_isolation' OR Variable_name = 'character_set_results' OR Variable_name = 'timezone' OR Variable_name = 'time_zone' OR Variable_name = 'system_time_zone' OR Variable_name = 'lower_case_table_names' OR Variable_name = 'max_allowed_packet' OR Variable_name = 'net_buffer_length' OR Variable_name = 'sql_mode' OR Variable_name = 'query_cache_type' OR Variable_name = 'query_cache_size' OR Variable_name = 'license' OR Variable_name = 'init_connect'/
/* mysql-connector-java-5.1.35 ( Revision: 5fb9c5849535c13917c2cf9baaece6ef9693ef27 ) */SELECT @@session.auto_increment_increment/
_W	J
SET NAMES latin1/
_l	J
SET character_set_results = NULL/
SET autocommit=1/
SET sql_mode='STRICT_TRANS_TABLES'/
SHOW DATABASES/
<+"@
4+#@
4+$@
u+%@
root
mysql_native_password
8+&@
9+'@
/* mysql-connector-java-5.1.35 ( Revision: 5fb9c5849535c13917c2cf9baaece6ef9693ef27 ) */SHOW VARIABLES WHERE Variable_name ='language' OR Variable_name = 'net_write_timeout' OR Variable_name = 'interactive_timeout' OR Variable_name = 'wait_timeout' OR Variable_name = 'character_set_client' OR Variable_name = 'character_set_connection' OR Variable_name = 'character_set' OR Variable_name = 'character_set_server' OR Variable_name = 'tx_isolation' OR Variable_name = 'transaction_isolation' OR Variable_name = 'character_set_results' OR Variable_name = 'timezone' OR Variable_name = 'time_zone' OR Variable_name = 'system_time_zone' OR Variable_name = 'lower_case_table_names' OR Variable_name = 'max_allowed_packet' OR Variable_name = 'net_buffer_length' OR Variable_name = 'sql_mode' OR Variable_name = 'query_cache_type' OR Variable_name = 'query_cache_size' OR Variable_name = 'license' OR Variable_name = 'init_connect'/
/* mysql-connector-java-5.1.35 ( Revision: 5fb9c5849535c13917c2cf9baaece6ef9693ef27 ) */SELECT @@session.auto_increment_increment/
I+*@
SET NAMES latin1/
Y++@
SET character_set_results = NULL/
I+,@
SET autocommit=1/
[+-@
SET sql_mode='STRICT_TRANS_TABLES'/
d+.@
SHOW FULL TABLES FROM `test\_test` LIKE '%'/
9+/@
4+0@
^C31 packets captured
62 packets received by filter
0 packets dropped by kernel
```
the sql "SHOW FULL TABLES FROM `test\_test` LIKE '%'" can not execute at mysql server for me.
```text
mysql> SHOW FULL TABLES FROM `test\_test` LIKE '%';
1049 - Unknown database 'test\_test'
```

and I use idea IDE  to debug 

![- 2015 11 20 - 18 24 23](https://cloud.githubusercontent.com/assets/3821439/11297597/71d73dee-8fb4-11e5-9d5b-6dfa42a1b4c5.png)

**Comment by kokosing** [comment]
```bash
$ docker run --name mariadb -e MYSQL_ROOT_PASSWORD=mariadb -e MYSQL_DATABASE=mariadb -e MYSQL_USER=mariadb -e MYSQL_PASSWORD=mariadb -p 3306:3306 -d mariadb
... table creatin
$ echo 'show tables;' |  mysql -P 3306 -u mariadb -h 192.168.0.93 -p mariadb
Tables_in_mariadb
test_table
$ echo 'SHOW VARIABLES LIKE "%version%";' |  mysql -P 3306 -u mariadb -h 192.168.0.93 -p mariadb
Enter password: 
Variable_name   Value
innodb_version  5.6.26-74.0
protocol_version        10
slave_type_conversions  
version 10.0.22-MariaDB-1~jessie
version_comment mariadb.org binary distribution
version_compile_machine x86_64
version_compile_os      debian-linux-gnu
version_malloc_library  bundled jemalloc
$ cat catalog/mariadb.properties 
connector.name=mysql
connection-url=jdbc:mysql://192.168.0.93
connection-user=mariadb
connection-password=mariadb
$ echo 'select * from mariadb.mariadb.test_table;' | presto-cli --server localhost:8080
presto> select * from mariadb.mariadb.test_table;
 1 
---
 1 
(1 row)

Query 20151120_140747_00014_9tyku, FINISHED, 1 node
Splits: 2 total, 2 done (100,00%)
0:00 [1 rows, 0B] [19 rows/s, 0B/s]

presto> 
$ echo 'select * from test_table;' |  mysql -P 3306 -u mariadb -h 192.168.0.93 -p mariadb
Enter password: 
1
1
```

Test with a table containing ``_`` worked... ; / I will try with database now.

**Comment by kokosing** [comment]
```bash
$ echo 'select * from test_table;' |  mysql -P 3306 -u mariadb -h 192.168.0.93 -p test_database
Enter password: 
2
2
$ echo 'select * from mariadb.test_database.test_table;' | presto-cli --serv
er localhost:8080
presto> select * from mariadb.test_database.test_table;
Query 20151120_141748_00015_9tyku failed: line 1:15: Table mariadb.test_database.test_table does not exist
select * from mariadb.test_database.test_table

presto> 
$ echo 'show schemas from mariadb;' | presto-cli --server localhost:8080presto> show schemas from mariadb;
       Schema       
--------------------
 information_schema 
 mariadb            
 test_database      
(3 rows)

Query 20151120_141815_00016_9tyku, FINISHED, 1 node
Splits: 2 total, 2 done (100,00%)
0:00 [3 rows, 57B] [75 rows/s, 1,4KB/s]

presto> 
$ echo 'show tables from mariadb.test_database;' | presto-cli --server localhost:8080
presto> show tables from mariadb.test_database;
 Table 
-------
(0 rows)

Query 20151120_141836_00017_9tyku, FINISHED, 1 node
Splits: 2 total, 2 done (100,00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

presto> 
```

Ok, I reproduced it. When a database contains ``_`` then I am not able to list its tables.

**Comment by kokosing** [comment]
@sunli1223 I have just posted an pull request #4006 it is very similar to what you suggested, can you check if it fixes your problem?

**Comment by sunli1223** [comment]
@kokosing  yes,It's worked for me.thank you.

**Comment by uranusmars** [comment]
@kokosing @sunli1223 great job, thank you two : )

**Comment by amrutagokhale** [comment]
I was testing something in postgresql and noticed that postgresql also suffers from this.

**Comment by kokosing** [comment]
Regarding similar behaviour for postgres connector. I was unable to reproduce it so I suspect it is totally different issue. I put underscore in database, schema and table name and still I was able to access them.

*presto*
```
presto> select * from postgres.test_schema.test_table2;
 t 
---
(0 rows)

Query 20151127_073927_00004_ju4bn, FINISHED, 1 node
Splits: 2 total, 2 done (100,00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

presto> show tables from postgres.test_schema;
    Table    
-------------
 test_table2 
(1 row)

Query 20151127_073936_00005_ju4bn, FINISHED, 1 node
Splits: 2 total, 2 done (100,00%)
0:00 [1 rows, 40B] [8 rows/s, 335B/s]

presto>
```

*connector*
```bash
$ cat presto-main/etc/catalog/postgres.properties 
connector.name=postgresql
connection-url=jdbc:postgresql://localhost:5432/test_database
connection-user=postgres
connection-password=postgres
```

**Comment by uranusmars** [comment]
Postgres seems good in our environment.

**Comment by amrutagokhale** [comment]
As noted by @kokosing , postgre case related to pg_catalog is unrelated to this "_" issue.

**Comment by kokosing** [comment]
Fix landed in the master, 0.128 release should not suffer for this any longer.

**Comment by barbarosyildiz** [comment]
presto-server-0.139 still have this problem .

Create database in mysql:
CREATE DATABASE TUTORIAL_1;
USE TUTORIAL_1;
 CREATE TABLE USERS (userid VARCHAR(15), gender CHAR(1), Age SMALLINT,country VARCHAR(50), SIGN_UP VARCHAR(50));

presto> SHOW TABLES FROM mysql.TUTORIAL_1;
 Table 
-------
(0 rows)

Query 20160301_082814_00005_fjdbm, FINISHED, 2 nodes
Splits: 2 total, 2 done (100.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

**Comment by SonuSingh200190** [comment]
I am also facing same issue. 
Database - RETAIL5M
Tables - ITEM, SALES, STORE, ONLINE_SALES, SALES_TEST.

Presto is not able to read this metadata, Please help.
![image](https://user-images.githubusercontent.com/33202006/88192035-b0e25500-cc59-11ea-9ff1-d7950f0261fd.png)
![image](https://user-images.githubusercontent.com/33202006/88192074-bfc90780-cc59-11ea-9432-9966bdf9c300.png)
